title: Kib's Reinforcement Learning
description: > # this means to ignore newlines until "baseurl:"
  Hey 👋  Welcome to my blog! 🤗 Learn about my journey towards mastering reinforcement learning! 💪
permalink: ':title/'
baseurl: "/RL_tools" # the subpath of your site, e.g. /blog
url: "https://kibeomkim14.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kibeom Kim🇨🇭🇬🇧🇰🇷 # add your name
author-img: kibeom-kim.jpg # add your photo
about-author: 4th gen quant. 
My interest lies in machine learning and finance. 
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kibeomkim14 # add your Github handle
social-linkedin: /edward-kim-013487113/ # add your Linkedin handle
social-email: kkb99705119@gmail.com # add your Email address

# Disqus
discus-identifier: kibeomkim14 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
